{
 "title": "Стенд iВолга",
 "time": { "from": "2018-07-31T12:50:00.000Z", "to": "2018-07-31T15:00:00.000Z" },
 "panels": [
  { "title": "Панель управления стендом", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Likes 👍",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "sensors",
     "query": "SELECT sum(\"value\") FROM \"sensors\" WHERE (\"topic\" = '/sensors/like')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/like" }
     ]
    }
   ]
  },
  {
   "title": "Устройство включено",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 1 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/power" }
     ]
    }
   ]
  },
  {
   "title": "Отключения датчика освещенности",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "*",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/disable_light" }
     ]
    }
   ]
  },
  {
   "title": "Текущее состояние лампы",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 5, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "sensors",
     "query": "SELECT last(\"value\") FROM \"sensors\" WHERE (\"topic\" = '/sensors/lamp')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/lamp" }
     ]
    }
   ]
  },
  {
   "title": "История изменения состояний",
   "type": "table",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/lamp" }
     ]
    }
   ]
  },
  {
   "title": "Средние значения освещенности",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "За 5 мин.",
     "measurement": "sensors",
     "query": "SELECT  867941.072 / pow((mean(\"value\") -10), 1.5832)  FROM \"sensors\" WHERE (\"topic\" = '/sensors/light') AND time < now() - 5m GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/light" }
     ]
    },
    {
     "alias": "За 15 мин.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 867941.072 / pow((mean(\"value\") -10), 1.5832)  FROM \"sensors\" WHERE (\"topic\" = '/sensors/light') AND time < now() - 15m GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "За 60 мин.",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT 867941.072 / pow((mean(\"value\") -10), 1.5832)  FROM \"sensors\" WHERE (\"topic\" = '/sensors/light') AND time < now() - 60m GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Оповещения", "type": "alertlist", "gridPos": { "h": 5, "w": 7, "x": 17, "y": 5 } },
  {
   "title": "Последнее изменение",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 5, "y": 6 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    {
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/lamp" }
     ]
    }
   ]
  },
  {
   "title": "Измерение освещенности",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "люкс",
     "groupBy": [
      { "params": [ "user" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "query": "SELECT 867941.072 / pow((\"value\" -10), 1.5832)   FROM \"sensors\" WHERE (\"topic\" = '/sensors/light' AND \"user\" = 'device') AND $timeFilter GROUP BY \"user\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ],
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/light" },
      { "condition": "AND", "key": "user", "operator": "=", "value": "device" }
     ]
    }
   ]
  },
  {
   "title": "Продолжительность периодов работы",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 3, "w": 13, "x": 11, "y": 10 },
   "targets": [
    {
     "alias": "*",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "/sensors/lamp" }
     ]
    }
   ]
  },
  {
   "title": "Дополнительные экраны",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Состояние датчика освещенности",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_user",
       "groupBy": [
        { "params": [ "user" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "value" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "/sensors/light" },
        { "condition": "AND", "key": "user", "operator": "=", "value": "device" }
       ]
      }
     ]
    },
    {
     "title": "Пример агрегации данных по цветовой шкале",
     "type": "natel-discrete-panel",
     "gridPos": { "h": 3, "w": 14, "x": 10, "y": 16 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Карта с установленными датчиками",
     "type": "grafana-worldmap-panel",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Средние значения температуры в аппаратной",
     "type": "heatmap",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 21 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "5m" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "sensors",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "topic", "operator": "=", "value": "/sensors/light" },
        { "condition": "AND", "key": "user", "operator": "=", "value": "device" }
       ]
      }
     ]
    },
    {
     "title": "Средние отклонения сигнала",
     "type": "graph",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}